spring:
  application:
    name: filter-server
  cloud:
    stream:
      bindings:
        publishElementUpdate-out-0:
          destination:  ${powsybl-ws.rabbitmq.destination.prefix:}element.update
      output-bindings: publishElementUpdate-out-0

powsybl:
  services:
    network-store-server:
      preloading-strategy: COLLECTION
      
powsybl-ws:
  database:
    name: filters

server:
  # TODO in the near future do we need spring 3.2 "server.tomcat.max-http-response-header-size" ?
  max-http-request-header-size: 64000
