spring:
  application:
    name: filter-server
  cloud:
    stream:
      bindings:
        publishElementUpdate-out-0:
          destination:  ${powsybl-ws.rabbitmq.destination.prefix:}element.update
      output-bindings: publishElementUpdate

powsybl:
  services:
    network-store-server:
      preloading-strategy: COLLECTION
      
powsybl-ws:
  database:
    name: filters

server:
  max-http-request-header-size: 64000
