ALTER TABLE identifier_list_filter ADD COLUMN equipment_type_temporary varchar;
UPDATE identifier_list_filter SET equipment_type_temporary = 'LINE' WHERE equipment_type = 0;
UPDATE identifier_list_filter SET equipment_type_temporary = 'GENERATOR' WHERE equipment_type = 1;
UPDATE identifier_list_filter SET equipment_type_temporary = 'LOAD' WHERE equipment_type = 2;
UPDATE identifier_list_filter SET equipment_type_temporary = 'SHUNT_COMPENSATOR' WHERE equipment_type = 3;
UPDATE identifier_list_filter SET equipment_type_temporary = 'STATIC_VAR_COMPENSATOR' WHERE equipment_type = 4;
UPDATE identifier_list_filter SET equipment_type_temporary = 'BATTERY' WHERE equipment_type = 5;
UPDATE identifier_list_filter SET equipment_type_temporary = 'BUS' WHERE equipment_type = 6;
UPDATE identifier_list_filter SET equipment_type_temporary = 'BUSBAR_SECTION' WHERE equipment_type = 7;
UPDATE identifier_list_filter SET equipment_type_temporary = 'DANGLING_LINE' WHERE equipment_type = 8;
UPDATE identifier_list_filter SET equipment_type_temporary = 'LCC_CONVERTER_STATION' WHERE equipment_type = 9;
UPDATE identifier_list_filter SET equipment_type_temporary = 'VSC_CONVERTER_STATION' WHERE equipment_type = 10;
UPDATE identifier_list_filter SET equipment_type_temporary = 'TWO_WINDINGS_TRANSFORMER' WHERE equipment_type = 11;
UPDATE identifier_list_filter SET equipment_type_temporary = 'THREE_WINDINGS_TRANSFORMER' WHERE equipment_type = 12;
UPDATE identifier_list_filter SET equipment_type_temporary = 'HVDC_LINE' WHERE equipment_type = 13;
UPDATE identifier_list_filter SET equipment_type_temporary = 'SUBSTATION' WHERE equipment_type = 14;
UPDATE identifier_list_filter SET equipment_type_temporary = 'VOLTAGE_LEVEL' WHERE equipment_type = 15;
ALTER TABLE identifier_list_filter DROP COLUMN equipment_type;
ALTER TABLE identifier_list_filter RENAME COLUMN equipment_type_temporary TO equipment_type;