server:
  port: 5027

spring:
  rabbitmq:
    addresses: localhost

powsybl-ws:
  database:
    host: localhost

backing-services:
  case:
    base-uri: http://localhost:5000

network-store-server:
  base-uri: http://localhost:8080/
